"""
Download selected COCO 2017 classes and export split annotations without copying images.

Usage:
    python -m scripts.tools.download_coco2017_by_class --output-root data/coco_filtered

Example:
    python -m scripts.tools.download_coco2017_by_class \
        --output-root data/coco_filtered \
        --classes bowl laptop "cell phone" remote book backpack handbag suitcase toothbrush

Output layout:
    <output-root>/
      train/
        _annotations.coco.json
      valid/
        _annotations.coco.json
      test/
        _annotations.coco.json

Download source:
    The raw COCO files are downloaded by FiftyOne into its default cache,
    and the exported annotation files under <output-root> point back to those cached images.
"""

import argparse
import json
import shutil
from pathlib import Path

import fiftyone as fo
import fiftyone.zoo as foz
from PIL import Image

SPLIT_EXPORT_NAMES = {
    "train": "train",
    "validation": "valid",
    "test": "test",
}


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description=(
            "Download COCO 2017 samples with FiftyOne and export COCO "
            "annotations that point to the FiftyOne cache"
        )
    )
    parser.add_argument(
        "--output-root",
        required=True,
        help="Directory where the exported COCO-format dataset should be written",
    )
    parser.add_argument(
        "--classes",
        nargs="+",
        default=[
            "bowl",
            "laptop",
            "cell phone",
            "remote",
            "book",
            "backpack",
            "handbag",
            "suitcase",
            "toothbrush",
        ],
        help='Class names to filter, for example: --classes bowl laptop "cell phone" remote',
    )
    return parser.parse_args()


def rewrite_annotation_file_names(dataset: fo.Dataset, labels_path: Path) -> None:
    """Rewrite COCO file_name entries to point to cached images."""
    file_name_to_path = {}
    for sample in dataset.iter_samples(progress=True):
        sample_path = Path(sample.filepath)
        file_name_to_path[sample_path.name] = sample_path.as_posix()

    with labels_path.open("r", encoding="utf-8") as f:
        coco_data = json.load(f)

    missing_files: list[str] = []
    for image in coco_data.get("images", []):
        exported_name = Path(image["file_name"]).name
        cached_path = file_name_to_path.get(exported_name)
        if cached_path is None:
            missing_files.append(exported_name)
            continue
        image["file_name"] = cached_path

    if missing_files:
        preview = ", ".join(missing_files[:5])
        raise ValueError(
            "Failed to map some exported COCO image names back to the FiftyOne cache: "
            f"{preview}"
        )

    with labels_path.open("w", encoding="utf-8") as f:
        json.dump(coco_data, f, ensure_ascii=False)


def export_unlabeled_split(dataset: fo.Dataset, labels_path: Path) -> None:
    """Write a COCO-style image list for unlabeled splits such as COCO test."""
    images: list[dict] = []
    for image_id, sample in enumerate(dataset.iter_samples(progress=True), start=1):
        image_path = Path(sample.filepath)
        metadata = getattr(sample, "metadata", None)
        width = getattr(metadata, "width", None)
        height = getattr(metadata, "height", None)

        if width is None or height is None:
            with Image.open(image_path) as img:
                width, height = img.size

        images.append(
            {
                "id": image_id,
                "file_name": image_path.as_posix(),
                "width": int(width),
                "height": int(height),
            }
        )

    coco_data = {
        "images": images,
        "annotations": [],
        "categories": [],
    }
    with labels_path.open("w", encoding="utf-8") as f:
        json.dump(coco_data, f, ensure_ascii=False)


def resolve_exported_labels_path(export_root: Path) -> Path:
    """Find the actual COCO annotation file generated by FiftyOne."""
    candidates = sorted(export_root.rglob("*.json"))
    if not candidates:
        raise FileNotFoundError(f"No exported annotation json found under {export_root}")

    for candidate in candidates:
        if candidate.name == "_annotations.coco.json":
            return candidate

    for candidate in candidates:
        if candidate.name == "labels.json":
            return candidate

    return candidates[0]


def export_split(dataset: fo.Dataset, output_root: Path, split_name: str) -> None:
    """Export one split as COCO annotations only."""
    export_split_name = SPLIT_EXPORT_NAMES[split_name]
    split_dir = output_root / export_split_name
    labels_path = split_dir / "_annotations.coco.json"
    temp_export_root = output_root / "_export_tmp"
    temp_export_dir = temp_export_root / export_split_name

    split_dir.mkdir(parents=True, exist_ok=True)
    temp_export_root.mkdir(parents=True, exist_ok=True)

    if labels_path.exists():
        labels_path.unlink()
    if temp_export_dir.exists():
        shutil.rmtree(temp_export_dir)
    temp_export_dir.mkdir(parents=True, exist_ok=True)

    if split_name == "test":
        export_unlabeled_split(dataset, labels_path)
        shutil.rmtree(temp_export_dir)
        if temp_export_root.exists() and not any(temp_export_root.iterdir()):
            temp_export_root.rmdir()
        print(f"Exported unlabeled split: {split_name} -> {split_dir}")
        return

    dataset.export(
        export_dir=str(temp_export_dir),
        dataset_type=fo.types.COCODetectionDataset,
        export_media=False,
    )

    exported_labels_path = resolve_exported_labels_path(temp_export_dir)
    shutil.move(str(exported_labels_path), str(labels_path))
    shutil.rmtree(temp_export_dir)
    if temp_export_root.exists() and not any(temp_export_root.iterdir()):
        temp_export_root.rmdir()

    if not labels_path.exists():
        raise FileNotFoundError(f"Expected exported annotation file at: {labels_path}")

    rewrite_annotation_file_names(dataset, labels_path)
    print(f"Exported split: {split_name} -> {split_dir}")


def download_split(split_name: str, classes: list[str]) -> fo.Dataset:
    """Download one split via FiftyOne zoo."""
    dataset = foz.load_zoo_dataset(
        "coco-2017",
        split=split_name,
        shuffle=(split_name == "train"),
        classes=classes,
        label_types=["detections", "segmentations"],
    )
    print(f"Downloaded split: {split_name}")
    return dataset


def main() -> None:
    """Program entry point."""
    args = parse_args()
    output_root = Path(args.output_root)
    output_root.mkdir(parents=True, exist_ok=True)

    for split_name in ("train", "validation", "test"):
        dataset = download_split(split_name, args.classes)
        export_split(dataset, output_root, split_name)


if __name__ == "__main__":
    main()
